url: https://kamtoeddy.github.io/agile-ninjas
baseurl: /agile-ninjas

# Site settings
title: Agile Ninjas
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
  - name: Tayo Daramola
    pic: 2
    position: Scrum Master

  - name: Augustina Onwubuya
    pic: augustina-picture
    position: Assistant Scrum Master
    social:
      - title: linkedin
        url: http://www.linkedin.com/in/Tina5110

  - name: Michael Collins
    pic: michael-picture
    position: Product Owner

  - name: Kamto Eddy
    pic: eddy-picture
    position: Software Engineer
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/kaed/
      - title: twitter
        url: https://twitter.com/eddy_kamto

  - name: Akangwa Willensky
    pic: willensky-picture
    position: Software Engineer

  - name: Shey Anabell
    pic: anabell-picture
    position: QA Engineer

  - name: Ekwoge Njitor
    pic: 2
    position: QA Engineer

  - name: Victor Enebeli
    pic: 2
    position: QA Engineer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
