url: https://kamtoeddy.github.io/agile-ninjas
baseurl: /agile-ninjas

# Site settings
title: Agile Ninjas
email: your-email@domain.com
description: "We thrive whilst working independently or as part of a group. We are fast, agile, and focused."

# Team names, titles and social links
people:
  - name: Tayo Daramola
    pic: tayo.jpg
    role: Scrum Master
    social:
      - title: linkedin
        url: http://www.LinkedIn.com/in/tayo-daramola

  - name: Augustina Onwubuya
    pic: augustina.jpg
    role: Assistant Scrum Master
    social:
      - title: linkedin
        url: http://www.linkedin.com/in/Tina5110

  - name: Michael Collins
    pic: michael.jpg
    role: Product Owner
    social:
      - title: linkedin
        url: http://www.linkedin.com/in/ssendegeya-kyeyune
      - title: envelope
        url: mailto:ssendegeyakyeyune@gmail.com

  - name: Kamto Eddy
    pic: eddy.jpg
    role: Software Engineer
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/kaed/
      - title: twitter
        url: https://twitter.com/eddy_kamto

  - name: Akangwa Willensky
    pic: willensky.jpg
    role: Software Engineer

  - name: Shey Anabell
    pic: anabell.jpg
    role: QA Engineer

  - name: Ekwoge Njitor
    pic: armstrong.jpg
    role: QA Engineer

  - name: Victor Enebeli
    pic: victor.png
    role: QA Engineer
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/victor-enebeli-639120231

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/
  # - title: bitbucket
  #   url: http://bitbucket.org/
  - title: github
    url: https://github.com/kamtoeddy/agile-ninjas

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
